version: "3.2"

# This is a docker-compose file designed to be called in macOS and translate through to windows

services:
  agent:
    build:
      dockerfile: .buildkite/Dockerfile-windows
      context: ../
    volumes:
      - ../:c:/work
    working_dir: c:/work
    tty: false
    environment:
      - BUILDKITE_BUILD_NUMBER
      - "BUILDKITE_BUILD_PATH=c:\\buildkite\\builds"

networks:
  default:
    external:
      name: nat
